# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('reciver_deleted', models.BooleanField(default=False)),
                ('deliver_deleted', models.BooleanField(default=False)),
                ('delivery_date', models.DateTimeField(auto_now=True)),
                ('mssg_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_from', to=settings.AUTH_USER_MODEL)),
                ('mssg_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
