# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmssg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='been_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivery_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
