# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 13:29
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('color', colorful.fields.RGBColorField()),
            ],
        ),
    ]
